### PR TITLE
DOCSP-5746 doc update for data lake related limitations

### PR DESCRIPTION
**Pull request by kanchana-mongodb**
JIRA: https://jira.mongodb.org/browse/DOCSP-5746
Stage links:
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/performance.html#limitations
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/databases.html#limitations
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/import-export.html#limitations
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/documents/insert.html#limitation
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/query-plan.html#visual-tree
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/indexes.html#limitations
https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/validation.html

### CODE REVIEW

**Comment by ckalmanek** [comment]
Kanchana,   I have two corrections:
1) https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/query-plan.html#visual-tree.   The explain plan tab doesn't work in either mode (visual tree or raw JSON) with a Data Lake.  (Data Lake supports explain but Compass needs to be updated to support it).
2) https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/collections.html.   After collection details, there is a list of features, some of which aren't supported in Community Edition.   This list should be updated with the features that aren't available in a Data Lake.

**Comment by kanchana-mongodb** [comment]
> Kanchana, I have two corrections:
> 
> 1. https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/query-plan.html#visual-tree.   The explain plan tab doesn't work in either mode (visual tree or raw JSON) with a Data Lake.  (Data Lake supports explain but Compass needs to be updated to support it).
> 2. https://docs-mongodbcom-staging.corp.mongodb.com/compass/kanchanasekhar/DOCSP-5746/collections.html.   After collection details, there is a list of features, some of which aren't supported in Community Edition.   This list should be updated with the features that aren't available in a Data Lake.

@ckalmanek - thanks for the feedback!
doc updated for #1; please review and provide feedback. 
for #2, can you please provide the list of features that are not supported in community edition or point me to the ticket where this information is available if it exists?

**Comment by ckalmanek** [comment]
For feedback #2, I think my comment might have been confusing.    I was simply suggesting that under “Collection Details” you add Compass features that are not supported on Data Lake to the bullet list following the screenshot.   It’s the same list of features that are covered in this PR.    I wasn’t suggesting that you make any changes to documentation about Compass Community edition.

**Comment by ckalmanek** [comment]
Community Edition will be going away with the open sourcing of Compass, but that's work that should be covered in a separate ticket.

**Comment by kanchana-mongodb** [comment]
> For feedback #2, I think my comment might have been confusing. I was simply suggesting that under “Collection Details” you add Compass features that are not supported on Data Lake to the bullet list following the screenshot. It’s the same list of features that are covered in this PR. I wasn’t suggesting that you make any changes to documentation about Compass Community edition.

Thanks for clarifying. Doc updated. Please review and provide feedback.

**Comment by ckalmanek** [comment]
lgtm.   i think it wasn't possible to add me as a reviewer, but i approve this PR

**Pull request merged**
