### PR TITLE
DOCSP-38793 updating minimum ubuntu and RHEL version

### PR DESCRIPTION
**Pull request by ltran-mdb2**
## DESCRIPTION

Updating minimum Ubuntu version to 16.04
(release note update will happen in the release note ticket)

## STAGING

https://preview-mongodbltranmdb2.gatsbyjs.io/compass/DOCSP-38793/install/#software-requirements-2

## JIRA

https://jira.mongodb.org/browse/DOCSP-38793

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663290b6b67dbf804a0a0997

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Is this free of spelling errors?
- [x] Is this free of grammatical errors?
- [x] Is this free of staging / rendering issues?
- [x] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

### CODE REVIEW

**Review by jmd-mongo — APPROVED** [review]
Thanks for this fix, @ltran-mdb2! This one LGTM.

Thanks,
Joe

**Review by addaleax — APPROVED** [review]
LGTM but just to be clear, this doesn't fully address DOCSP-38793

**Comment by ltran-mdb2** [comment]
Discussed with Anna and  is addressed the rest of this ticket in  [DOCSP-39158](https://jira.mongodb.org/browse/DOCSP-39158)

**Comment by addaleax** [comment]
Err, now I'm confused, I thought you wanted to address the RHEL bump in a separate ticket?

**Comment by addaleax** [comment]
To be clear, the page updated in this PR _also_ needs to be updated re: dropped RHEL7 support, that's the main point of the JIRA ticket linked here, it's fine if that happens in a separate ticket/PR, but it should happen :)

**Review by addaleax — APPROVED** [review]

**Pull request merged**
